// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLz2srK54Ug3fpYH9LwoxpHaz8vmwAqow',
    appId: '1:404625422784:web:41ee56cd6896d5f008f025',
    messagingSenderId: '404625422784',
    projectId: 'music-class-af41e',
    authDomain: 'music-class-af41e.firebaseapp.com',
    storageBucket: 'music-class-af41e.firebasestorage.app',
    measurementId: 'G-D0W4P2TG29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4fHkTdVGPkWOhnrD_xnZnCbTeQyciajs',
    appId: '1:404625422784:android:3f8381a925f0a6d708f025',
    messagingSenderId: '404625422784',
    projectId: 'music-class-af41e',
    storageBucket: 'music-class-af41e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLz2srK54Ug3fpYH9LwoxpHaz8vmwAqow',
    appId: '1:404625422784:web:7c478bd9dc4dff3308f025',
    messagingSenderId: '404625422784',
    projectId: 'music-class-af41e',
    authDomain: 'music-class-af41e.firebaseapp.com',
    storageBucket: 'music-class-af41e.firebasestorage.app',
    measurementId: 'G-52JJGQPJLE',
  );
}
